name: CD

on: workflow_call

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download a Build Artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: binary
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: /home/${{ secrets.SSH_REMOTE_USER }}
          EXCLUDE: "postgres-data"
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export                                  \
              HOST="${{ secrets.DB_HOST }}"         \
              USER="${{ secrets.DB_USER }}"         \
              PASSWORD="${{ secrets.DB_PASSWORD }}" \
              DBNAME="${{ secrets.DB_NAME }}"       \
              DBPORT="${{ secrets.DB_PORT }}"       \
              PORT=8000

            echo $HOST $USER $PASSWORD $DBNAME $DBPORT $PORT

            chmod +x ./main
            nohup ./main > nohup.out 2> nohup.err < /dev/null &

